# only look for features in this region (pixel)
roi:
    x_min: 200
    x_max: 900
    y_min: 40
    y_max: 280

# discard data when theese limits are not met
limits:
    vx_max: 5
    vx_min: -0.1
    vy_max: 5
    vy_min: -0.1
    omega_max: 0.5
    omega_min: -0.5
